### PR TITLE
Sigma convolution

### PR DESCRIPTION
**Pull request by AnderGray**
Adds sigma convolution for performing correlated operations.

- Inputs: 2 pboxes, a (positive) binary operator and a copula
- Computes: the resulting pbox from the binary operator following the copula dependence

Added methods:
- sigma: main convolution function
- correlated option to `+,-,*,/`, as `method = 'c'` (correlated) and corr argument (default 0)

eg:
```python
d = pba.U(0,1)
f = d.sigma(d, lambda x,y: x+y, pba.Gaussian(0.5))   # Binary operator must be given as lambda function 

f = d.add(d, method = 'c', corr = 0.5)  # Does the same above. Default copula is gaussian
```

### CODE REVIEW

**Comment by AnderGray** [comment]
@ngg1995 any chance you could take a look?

**Comment by ngg1995** [comment]
I don't know how to do the merge without destroying other changes

**Comment by AnderGray** [comment]
Ok, will try and fix it. Maybe making a new PR will work

**Comment by AnderGray** [comment]
Did we merge it?

**Pull request closed without merging**
